# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ba9a9c6c119784ac271c43ee743d8d24424e12d98370d5c3b1448dae8c0b4c2acbc6354d0c5b4d3d765151659fed22efa0305aaf2886f53d685832c3cab011cf

test:
  secret_key_base: 6707238f361c844f02b80c998e73c513fa9fc3690e98f261e5d72b838216f29082f7fc916639ff73c52ef77ef439190588302161ab173627902a4021a5b11596

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
